### ISSUE TITLE
Using App export directly without ExpressReceiver

### ISSUE THREAD

**Issue by ryan-0** [seratch/bolt-on-cloud-functions-for-firebase#5]
Hi, 
I am wondering if you know of a way or workaround to use the default `App` from `@slack/bolt` without using the explicit `ExpressReceiver` as is being done in this example, and still get it to work with cloud functions. I'm asking because I want to take advantage of the built-in `auth` handling that you can use when just using `App` (https://slack.dev/bolt-js/concepts#authenticating-oauth) instead of using `ExpressReceiver` and re-implementing auth using the oAuth library.

**Comment by ryan-0** [comment]
This feels related to the following issue: 
https://github.com/slackapi/bolt-js/issues/191

**Comment by seratch** [comment]
At this point, manually initializing `ExpressReceiver` is a recommended way because of the reasons you've mentioned. Initializing `ExpressReceiver` doesn't prevent you from utilizing the `@slack/oauth` package. You can pass all the arguments (clientId, clientSecret, installationStore, and so on) in `App` constructor to it. https://github.com/slackapi/bolt-js/blob/%40slack/bolt%402.2.3/src/App.ts#L248-L259

**Comment by rosgoo** [comment]
Thanks! good to know. I'll close this issue for now!
